services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: dafon-cv-mysql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dafon-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: dafon-cv-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - dafon-network
    command: >
      redis-server
      --maxmemory ${REDIS_MAX_MEMORY}
      --maxmemory-policy ${REDIS_MAX_MEMORY_POLICY}
      --save ${REDIS_SAVE}
      --appendonly ${REDIS_APPENDONLY}
      --appendfsync ${REDIS_APPENDFSYNC}
    environment:
      - REDIS_MAX_MEMORY=${REDIS_MAX_MEMORY}
      - REDIS_MAX_MEMORY_POLICY=${REDIS_MAX_MEMORY_POLICY}
    deploy:
      resources:
        limits:
          memory: ${REDIS_MEMORY_LIMIT}
        reservations:
          memory: ${REDIS_MEMORY_RESERVATION}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 10s
      retries: 5

  # Go API Application
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dafon-cv-api
    restart: unless-stopped
    ports:
      - "${PORT:-8080}:8080"
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
      - REDIS_MAX_MEMORY=${REDIS_MAX_MEMORY}
      - REDIS_MAX_MEMORY_POLICY=${REDIS_MAX_MEMORY_POLICY}
      - REDIS_MEMORY_LIMIT=${REDIS_MEMORY_LIMIT}
      - REDIS_MEMORY_RESERVATION=${REDIS_MEMORY_RESERVATION}
      - RATE_LIMIT=${RATE_LIMIT}
      - RATE_WINDOW_MINUTES=${RATE_WINDOW_MINUTES}
      - AI_RATE_LIMIT=${AI_RATE_LIMIT}
      - AI_RATE_WINDOW_MINUTES=${AI_RATE_WINDOW_MINUTES}
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - dafon-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  dafon-network:
    driver: bridge 