package routes

import (
	_ "github.com/Daniel-Fonseca-da-Silva/dafon-cv-api/docs"
	"github.com/Daniel-Fonseca-da-Silva/dafon-cv-api/internal/cache"
	"github.com/Daniel-Fonseca-da-Silva/dafon-cv-api/internal/config"
	"github.com/Daniel-Fonseca-da-Silva/dafon-cv-api/internal/handlers"
	"github.com/Daniel-Fonseca-da-Silva/dafon-cv-api/internal/middleware"
	"github.com/Daniel-Fonseca-da-Silva/dafon-cv-api/internal/ratelimit"
	"github.com/Daniel-Fonseca-da-Silva/dafon-cv-api/internal/redis"
	"github.com/Daniel-Fonseca-da-Silva/dafon-cv-api/internal/repositories"
	"github.com/Daniel-Fonseca-da-Silva/dafon-cv-api/internal/usecases"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	"go.uber.org/zap"
	"gorm.io/gorm"
)

// SetupRoutes configures all application routes
func SetupRoutes(router *gin.Engine, db *gorm.DB, logger *zap.Logger, cfg *config.Config) error {
	// Initialize rate limiter with environment configuration
	rateLimiter := ratelimit.NewDefaultRateLimiter(redis.GetClient(), logger)

	// Apply rate limiting to all routes except health check
	router.Use(ratelimit.RateLimiterMiddleware(rateLimiter))

	// Health check handler
	healthHandler := handlers.NewHealthCheckHandler(logger)

	// Health check endpoint (no rate limiting)
	router.GET("/health", healthHandler.HealthCheck)

	// Swagger documentation (generated by swag init -g cmd/api/main.go)
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Session auth middleware (Magic Link token stored in sessions table)
	sessionRepo := repositories.NewSessionRepository(db)
	sessionAuthMiddleware := middleware.SessionMiddleware(sessionRepo)

	// Setup user routes
	SetupUserRoutes(router, db, logger, cfg, sessionAuthMiddleware)

	// Setup admin (back office) routes
	SetupAdminRoutes(router, db, logger, cfg)

	// Curriculum use case (shared by curriculum and generate-analyze-ai routes)
	cacheService := cache.NewCacheService(redis.GetClient(), logger)
	curriculumRepo := repositories.NewCurriculumRepository(db, logger)
	curriculumUseCase := usecases.NewCurriculumUseCase(curriculumRepo, cacheService, logger)

	// Setup curriculum routes
	SetupCurriculumRoutes(router, db, logger, cfg, sessionAuthMiddleware, curriculumUseCase)

	// Subscription usecase (used by subscription-gated endpoints)
	subscriptionRepo := repositories.NewSubscriptionRepository(db, logger)
	userRepo := repositories.NewUserRepository(db, logger)
	subscriptionUseCase := usecases.NewSubscriptionUseCase(subscriptionRepo, userRepo, cfg.Stripe, logger)

	// Setup AI analysis routes
	SetupGenerateIntroAIRoutes(router, logger, cfg, sessionAuthMiddleware, subscriptionUseCase)
	// Setup generate courses AI routes
	SetupGenerateCoursesAIRoutes(router, logger, cfg, sessionAuthMiddleware, subscriptionUseCase)

	// Setup generate academic AI routes
	SetupGenerateAcademicAIRoutes(router, logger, cfg, sessionAuthMiddleware, subscriptionUseCase)

	// Setup generate task AI routes
	SetupGenerateTaskAIRoutes(router, logger, cfg, sessionAuthMiddleware, subscriptionUseCase)

	// Setup generate skill AI routes
	SetupGenerateSkillAIRoutes(router, logger, cfg, sessionAuthMiddleware, subscriptionUseCase)

	// Setup configuration routes
	SetupConfigurationRoutes(router, db, logger, cfg, sessionAuthMiddleware)

	// Setup authentication email routes
	SetupEmailRoutes(router, logger, cfg)

	// Setup generate analyze AI routes
	SetupGenerateAnalyzeAIRoutes(router, logger, cfg, sessionAuthMiddleware, subscriptionUseCase, curriculumUseCase)

	// Setup generate translation AI routes
	SetupGenerateTranslationAIRoutes(router, logger, cfg, sessionAuthMiddleware, subscriptionUseCase)

	// Setup subscriptions routes (Stripe)
	SetupSubscriptionRoutes(router, db, logger, cfg, sessionAuthMiddleware)

	return nil
}
