// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "DafonCV Support",
            "url": "https://www.dafoncv.online",
            "email": "dafondeveloper@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/admin/curriculums": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "UserIDHeader": []
                    }
                ],
                "description": "Returns paginated list of curriculums. Requires admin user (X-User-ID header).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Get curriculums (paginated)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cursor (UUID) to fetch items after",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.AdminCurriculumsListResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid pagination or sort params",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseValidation"
                        }
                    },
                    "401": {
                        "description": "X-User-ID header required",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Admin access required",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseServer"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/curriculums/stats": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "UserIDHeader": []
                    }
                ],
                "description": "Returns curriculums count. Requires admin user (X-User-ID header).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Get curriculums statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CurriculumsStatsResponse"
                        }
                    },
                    "401": {
                        "description": "X-User-ID header required",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Admin access required",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseServer"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/dashboard": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "UserIDHeader": []
                    }
                ],
                "description": "Returns dashboard summary (users and curriculums count). Requires admin user (X-User-ID header).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Get admin dashboard",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.DashboardResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseValidation"
                        }
                    },
                    "401": {
                        "description": "X-User-ID header required",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Admin access required",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseServer"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "UserIDHeader": []
                    }
                ],
                "description": "Returns paginated list of users. Requires admin user (X-User-ID header).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Get users (paginated)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cursor (UUID) to fetch items after",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.AdminUsersListResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid pagination params",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseValidation"
                        }
                    },
                    "401": {
                        "description": "X-User-ID header required",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Admin access required",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseServer"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/users/stats": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "UserIDHeader": []
                    }
                ],
                "description": "Returns users count. Requires admin user (X-User-ID header).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Get users statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UsersStatsResponse"
                        }
                    },
                    "401": {
                        "description": "X-User-ID header required",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Admin access required",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseServer"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/users/{id}/detail": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "UserIDHeader": []
                    }
                ],
                "description": "Returns a single user by ID. Requires admin user (X-User-ID header).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Get user detail by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid user ID format",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseValidation"
                        }
                    },
                    "401": {
                        "description": "X-User-ID header required",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Admin access required",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseServer"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/users/{id}/toggle-admin": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "UserIDHeader": []
                    }
                ],
                "description": "Toggles the admin flag for a user. Requires admin user (X-User-ID header).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Toggle user admin flag",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid user ID format",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseValidation"
                        }
                    },
                    "401": {
                        "description": "X-User-ID header required",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Admin access required",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseServer"
                        }
                    }
                }
            }
        },
        "/api/v1/configuration/{user_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the configuration for the given user ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configuration"
                ],
                "summary": "Get configuration by user ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ConfigurationResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid user ID format",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseValidation"
                        }
                    },
                    "404": {
                        "description": "Configuration not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseServer"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes the configuration for the given user ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configuration"
                ],
                "summary": "Delete configuration by user ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid user ID format",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseValidation"
                        }
                    },
                    "404": {
                        "description": "Configuration not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseServer"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates the configuration for the given user ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configuration"
                ],
                "summary": "Update configuration by user ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateConfigurationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ConfigurationResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid user ID format or validation error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseValidation"
                        }
                    },
                    "404": {
                        "description": "Configuration not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseServer"
                        }
                    }
                }
            }
        },
        "/api/v1/curriculums": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new curriculum for a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "curriculum"
                ],
                "summary": "Create curriculum",
                "parameters": [
                    {
                        "description": "Create payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateCurriculumRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.CurriculumResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error or invalid user ID",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseValidation"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseServer"
                        }
                    }
                }
            }
        },
        "/api/v1/curriculums/count-by-user/{user_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the number of curriculums for the given user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "curriculum"
                ],
                "summary": "Get curriculum count by user ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response with count field",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Invalid user ID format",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseValidation"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseServer"
                        }
                    }
                }
            }
        },
        "/api/v1/curriculums/creation-count-by-user/{user_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the total number of successful curriculum creations for the given user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "curriculum"
                ],
                "summary": "Get curriculum creation count by user ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response with total_creations field",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Invalid user ID format",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseValidation"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseServer"
                        }
                    }
                }
            }
        },
        "/api/v1/curriculums/get-all-by-user/{user_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns paginated list of curriculums for the given user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "curriculum"
                ],
                "summary": "Get all curriculums by user ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Cursor (UUID) to fetch items after",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CurriculumListResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid user ID or pagination params",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseValidation"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseServer"
                        }
                    }
                }
            }
        },
        "/api/v1/curriculums/get-body/{curriculum_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the curriculum content in text format",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "curriculum"
                ],
                "summary": "Get curriculum body",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Curriculum ID",
                        "name": "curriculum_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CurriculumBodyResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid curriculum ID format",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseValidation"
                        }
                    },
                    "404": {
                        "description": "Curriculum not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseServer"
                        }
                    }
                }
            }
        },
        "/api/v1/curriculums/{curriculum_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a curriculum by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "curriculum"
                ],
                "summary": "Get curriculum by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Curriculum ID",
                        "name": "curriculum_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CurriculumResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid curriculum ID format",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseValidation"
                        }
                    },
                    "404": {
                        "description": "Curriculum not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseServer"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a curriculum by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "curriculum"
                ],
                "summary": "Delete curriculum by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Curriculum ID",
                        "name": "curriculum_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid curriculum ID format",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseValidation"
                        }
                    },
                    "404": {
                        "description": "Curriculum not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseServer"
                        }
                    }
                }
            }
        },
        "/api/v1/generate-academic-ai": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Generates academic-style content from the given input",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Generate AI"
                ],
                "summary": "Generate academic content with AI",
                "parameters": [
                    {
                        "description": "Content to process",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.GenerateAcademicAIRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GenerateAcademicAIResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseValidation"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseServer"
                        }
                    }
                }
            }
        },
        "/api/v1/generate-analyze-ai": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Analyzes curriculum content and returns score, improvement points, ATS compatibility, and recommendations",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Generate AI"
                ],
                "summary": "Analyze curriculum with AI",
                "parameters": [
                    {
                        "description": "Curriculum content to analyze",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.GenerateAnalyzeAIRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GenerateAnalyzeAIResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseValidation"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseServer"
                        }
                    }
                }
            }
        },
        "/api/v1/generate-courses-ai": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Generates courses/training content from the given input",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Generate AI"
                ],
                "summary": "Generate courses content with AI",
                "parameters": [
                    {
                        "description": "Content to process",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.GenerateCoursesAIRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GenerateCoursesAIResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseValidation"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseServer"
                        }
                    }
                }
            }
        },
        "/api/v1/generate-intro-ai": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Generates professional introduction content from the given input",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Generate AI"
                ],
                "summary": "Generate intro content with AI",
                "parameters": [
                    {
                        "description": "Content to process",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.GenerateIntroAIRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GenerateIntroAIResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseValidation"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseServer"
                        }
                    }
                }
            }
        },
        "/api/v1/generate-skill-ai": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Generates related skills from the given input",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Generate AI"
                ],
                "summary": "Generate skills with AI",
                "parameters": [
                    {
                        "description": "Content to process",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.GenerateSkillAIRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GenerateSkillAIResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseValidation"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseServer"
                        }
                    }
                }
            }
        },
        "/api/v1/generate-task-ai": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Generates task/description content from the given input",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Generate AI"
                ],
                "summary": "Generate task content with AI",
                "parameters": [
                    {
                        "description": "Content to process",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.GenerateTaskAIRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GenerateTaskAIResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseValidation"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseServer"
                        }
                    }
                }
            }
        },
        "/api/v1/generate-translation-ai": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Translates curriculum content to the target language (pt, en, es)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Generate AI"
                ],
                "summary": "Translate curriculum with AI",
                "parameters": [
                    {
                        "description": "Curriculum to translate + target_language (pt, en, es)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.GenerateTranslationAIRequestDoc"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Translated curriculum (same structure as create curriculum)",
                        "schema": {
                            "$ref": "#/definitions/dto.CurriculumResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseValidation"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseServer"
                        }
                    }
                }
            }
        },
        "/api/v1/send-email": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Sends an authentication email with session token link",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "email"
                ],
                "summary": "Send authentication email",
                "parameters": [
                    {
                        "description": "Email payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.SendEmailRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SendEmailResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseValidation"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseServer"
                        }
                    }
                }
            }
        },
        "/api/v1/user": {
            "post": {
                "description": "Creates a new user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Create user",
                "parameters": [
                    {
                        "description": "Create payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseValidation"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseServer"
                        }
                    }
                }
            }
        },
        "/api/v1/user/all": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a list of all users",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Get all users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UsersResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseValidation"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseServer"
                        }
                    }
                }
            }
        },
        "/api/v1/user/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a user by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Get user by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid user ID format",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseValidation"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseServer"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a user by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Delete user by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid user ID format",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseValidation"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseServer"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates an existing user by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Update user by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid user ID format or validation error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseValidation"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponseServer"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.ATSCompatibility": {
            "type": "object",
            "properties": {
                "assessment": {
                    "type": "string"
                },
                "chance": {
                    "type": "string"
                },
                "recommendations": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "dto.AdminCurriculumsListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CurriculumResponse"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/dto.CursorPagination"
                }
            }
        },
        "dto.AdminUsersListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.UserResponse"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/dto.CursorPagination"
                }
            }
        },
        "dto.ConfigurationResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "language": {
                    "type": "string"
                },
                "newsletter": {
                    "type": "boolean"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "dto.CreateCurriculumRequest": {
            "type": "object",
            "required": [
                "driver_license",
                "email",
                "full_name",
                "intro",
                "languages",
                "phone",
                "skills",
                "user_id"
            ],
            "properties": {
                "courses": {
                    "type": "string"
                },
                "driver_license": {
                    "type": "string"
                },
                "educations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CreateEducationRequest"
                    }
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 5
                },
                "image_url": {
                    "type": "string"
                },
                "intro": {
                    "type": "string"
                },
                "languages": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "skills": {
                    "type": "string"
                },
                "social_links": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "works": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CreateWorkRequest"
                    }
                }
            }
        },
        "dto.CreateEducationRequest": {
            "type": "object",
            "required": [
                "degree",
                "description",
                "institution",
                "start_date"
            ],
            "properties": {
                "degree": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 2
                },
                "description": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 2
                },
                "end_date": {
                    "type": "string"
                },
                "institution": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 2
                },
                "start_date": {
                    "type": "string"
                }
            }
        },
        "dto.CreateUserRequest": {
            "type": "object",
            "required": [
                "email",
                "name"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "john@example.com"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 10,
                    "example": "John Doe"
                }
            }
        },
        "dto.CreateWorkRequest": {
            "type": "object",
            "required": [
                "company",
                "position",
                "start_date"
            ],
            "properties": {
                "company": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 2
                },
                "description": {
                    "type": "string"
                },
                "end_date": {
                    "description": "Nullable para trabalhos atuais",
                    "type": "string"
                },
                "position": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 2
                },
                "start_date": {
                    "type": "string"
                }
            }
        },
        "dto.CurriculumBodyResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                }
            }
        },
        "dto.CurriculumListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CurriculumResponse"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/dto.CursorPagination"
                }
            }
        },
        "dto.CurriculumResponse": {
            "type": "object",
            "properties": {
                "courses": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "driver_license": {
                    "type": "string"
                },
                "educations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.EducationResponse"
                    }
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "image_url": {
                    "type": "string"
                },
                "intro": {
                    "type": "string"
                },
                "languages": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "skills": {
                    "type": "string"
                },
                "social_links": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "works": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.WorkResponse"
                    }
                }
            }
        },
        "dto.CurriculumsStatsResponse": {
            "type": "object",
            "properties": {
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.CursorPagination": {
            "type": "object",
            "properties": {
                "cursor": {
                    "type": "string"
                },
                "has_next_page": {
                    "type": "boolean"
                },
                "limit": {
                    "type": "integer"
                },
                "next_cursor": {
                    "type": "string"
                }
            }
        },
        "dto.DashboardResponse": {
            "type": "object",
            "properties": {
                "curriculums_count": {
                    "type": "integer"
                },
                "users_count": {
                    "type": "integer"
                }
            }
        },
        "dto.EducationResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "degree": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "institution": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "user not found"
                }
            }
        },
        "dto.ErrorResponseServer": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Internal server error"
                }
            }
        },
        "dto.ErrorResponseValidation": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Validation error"
                }
            }
        },
        "dto.GenerateAcademicAIRequest": {
            "type": "object",
            "required": [
                "content"
            ],
            "properties": {
                "content": {
                    "type": "string",
                    "maxLength": 20000,
                    "minLength": 3
                }
            }
        },
        "dto.GenerateAcademicAIResponse": {
            "type": "object",
            "properties": {
                "filtered_content": {
                    "type": "string"
                }
            }
        },
        "dto.GenerateAnalyzeAIRequest": {
            "type": "object",
            "required": [
                "content"
            ],
            "properties": {
                "content": {
                    "type": "string",
                    "maxLength": 20000,
                    "minLength": 500,
                    "example": "string"
                }
            }
        },
        "dto.GenerateAnalyzeAIResponse": {
            "type": "object",
            "properties": {
                "ats_compatibility": {
                    "$ref": "#/definitions/dto.ATSCompatibility"
                },
                "best_practices": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "description": {
                    "type": "string"
                },
                "improvement_points": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "professional_alignment": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "recommendations": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "score": {
                    "type": "number"
                },
                "strengths": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "dto.GenerateCoursesAIRequest": {
            "type": "object",
            "required": [
                "content"
            ],
            "properties": {
                "content": {
                    "type": "string",
                    "maxLength": 20000,
                    "minLength": 3
                }
            }
        },
        "dto.GenerateCoursesAIResponse": {
            "type": "object",
            "properties": {
                "filtered_content": {
                    "type": "string"
                }
            }
        },
        "dto.GenerateIntroAIRequest": {
            "type": "object",
            "required": [
                "content"
            ],
            "properties": {
                "content": {
                    "type": "string",
                    "maxLength": 20000,
                    "minLength": 3
                }
            }
        },
        "dto.GenerateIntroAIResponse": {
            "type": "object",
            "properties": {
                "filtered_content": {
                    "type": "string"
                }
            }
        },
        "dto.GenerateSkillAIRequest": {
            "type": "object",
            "required": [
                "content"
            ],
            "properties": {
                "content": {
                    "type": "string",
                    "maxLength": 20000,
                    "minLength": 3
                }
            }
        },
        "dto.GenerateSkillAIResponse": {
            "type": "object",
            "properties": {
                "filtered_content": {
                    "type": "string"
                }
            }
        },
        "dto.GenerateTaskAIRequest": {
            "type": "object",
            "required": [
                "content"
            ],
            "properties": {
                "content": {
                    "type": "string",
                    "maxLength": 20000,
                    "minLength": 3
                }
            }
        },
        "dto.GenerateTaskAIResponse": {
            "type": "object",
            "properties": {
                "filtered_content": {
                    "type": "string"
                }
            }
        },
        "dto.GenerateTranslationAIRequestDoc": {
            "type": "object",
            "required": [
                "curriculum_data",
                "target_language"
            ],
            "properties": {
                "curriculum_data": {
                    "$ref": "#/definitions/dto.CurriculumResponse"
                },
                "target_language": {
                    "type": "string",
                    "enum": [
                        "pt",
                        "en",
                        "es"
                    ]
                }
            }
        },
        "dto.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "User deleted successfully"
                }
            }
        },
        "dto.SendEmailRequest": {
            "type": "object",
            "required": [
                "email",
                "name",
                "url_token"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2
                },
                "url_token": {
                    "type": "string",
                    "minLength": 1
                }
            }
        },
        "dto.SendEmailResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dto.UpdateConfigurationRequest": {
            "type": "object",
            "properties": {
                "language": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 2
                },
                "newsletter": {
                    "type": "boolean"
                }
            }
        },
        "dto.UpdateUserRequest": {
            "type": "object",
            "properties": {
                "admin": {
                    "type": "boolean"
                },
                "age": {
                    "type": "integer",
                    "minimum": 0
                },
                "city": {
                    "type": "string",
                    "maxLength": 255
                },
                "country": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "employment": {
                    "type": "boolean"
                },
                "gender": {
                    "type": "string",
                    "enum": [
                        "male",
                        "female"
                    ]
                },
                "image_url": {
                    "type": "string"
                },
                "migration": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 10
                },
                "phone": {
                    "type": "string"
                },
                "salary": {
                    "type": "number"
                },
                "state": {
                    "type": "string",
                    "maxLength": 255
                }
            }
        },
        "dto.UserResponse": {
            "type": "object",
            "properties": {
                "admin": {
                    "type": "boolean"
                },
                "age": {
                    "type": "integer"
                },
                "city": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "employment": {
                    "type": "boolean"
                },
                "gender": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "image_url": {
                    "type": "string"
                },
                "migration": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "salary": {
                    "type": "number"
                },
                "state": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dto.UsersResponse": {
            "type": "object",
            "properties": {
                "total": {
                    "type": "integer"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.UserResponse"
                    }
                }
            }
        },
        "dto.UsersStatsResponse": {
            "type": "object",
            "properties": {
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.WorkResponse": {
            "type": "object",
            "properties": {
                "company": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "position": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "UserIDHeader": {
            "type": "apiKey",
            "name": "X-User-ID",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Dafon CV API",
	Description:      "API for consultancy business and cv generation",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
